#!/bin/bash
set -e

PROJECT_PATH="${GITHUB_WORKSPACE}"
MIN_CONFIDENCE="${MIN_CONFIDENCE:-70}"
MIN_COMPLEXITY="${MIN_COMPLEXITY:-15}"
LANGUAGE="${LANGUAGE:-}"
REPO="${GITHUB_REPOSITORY}"
RUN_NUMBER="${GITHUB_RUN_NUMBER}"
TODAY=$(date +"%Y-%m-%d")

echo "☠ Archaeologist — Codebase Intelligence Report"
echo "Project: $PROJECT_PATH"
echo "Date: $TODAY"

# Build language flag
LANG_FLAG=""
if [ -n "$LANGUAGE" ]; then
    LANG_FLAG="--lang $LANGUAGE"
fi

# ── 1. Dead code ──────────────────────────────────────────────
echo ""
echo "Running dead code scan..."
DEAD_OUTPUT=$(deadcode "$PROJECT_PATH" --min-confidence "$MIN_CONFIDENCE" --limit 20 --explain 2>&1 || true)

# ── 2. Complexity ─────────────────────────────────────────────
echo "Running complexity scan..."
COMPLEXITY_OUTPUT=$(archaeologist-complexity "$PROJECT_PATH" --min-score "$MIN_COMPLEXITY" --limit 20 $LANG_FLAG 2>&1 || true)

# ── 3. Duplicates ─────────────────────────────────────────────
echo "Running duplicate scan..."
DUPES_OUTPUT=$(archaeologist-dupes "$PROJECT_PATH" 2>&1 || true)

# ── 4. Impact ─────────────────────────────────────────────────
echo "Running impact scan..."
IMPACT_OUTPUT=$(archaeologist-impact "$PROJECT_PATH" --all 2>&1 || true)

# ── Build GitHub Issue body ───────────────────────────────────
ISSUE_BODY="# ☠ Archaeologist Codebase Report — $TODAY

> Auto-generated by [Archaeologist](https://github.com/prathik-arun/archaeologist) · Run #$RUN_NUMBER

---

## ☠ Dead Code (confidence ≥ ${MIN_CONFIDENCE}%)

\`\`\`
$DEAD_OUTPUT
\`\`\`

---

## ◈ Complexity (score ≥ ${MIN_COMPLEXITY})

\`\`\`
$COMPLEXITY_OUTPUT
\`\`\`

---

## ⧉ Duplicates

\`\`\`
$DUPES_OUTPUT
\`\`\`

---

## ◎ Change Impact — Top Files by Blast Radius

\`\`\`
$IMPACT_OUTPUT
\`\`\`

---

*Run \`pip3 install archaeologist\` locally to get HTML reports and the interactive architecture graph.*
*[Website](https://prathik-arun.github.io/archaeologist) · [GitHub](https://github.com/prathik-arun/archaeologist)*"

# ── Post as GitHub Issue ──────────────────────────────────────
echo ""
echo "Posting report as GitHub Issue..."

ISSUE_TITLE="☠ Archaeologist Codebase Report — $TODAY"

curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/$REPO/issues" \
  -d "$(python3 -c "
import json, sys
title = sys.argv[1]
body = sys.argv[2]
print(json.dumps({'title': title, 'body': body, 'labels': ['archaeologist', 'codebase-report']}))
" "$ISSUE_TITLE" "$ISSUE_BODY")"

echo ""
echo "✓ Report posted as GitHub Issue!"
